### ISSUE TITLE
Odlazak na ostale stranice sa stranice /api/posaljitePromenu

### ISSUE THREAD

**Issue by Myoshu** [crtarsorg/koJeVlast#1]
@XoDevCom, u tvom commit-u [CleanUP: posaljite-promenu.php?... na api/posaljitePromenu](https://github.com/crtarsorg/koJeVlast/commit/adf74990da54fcfe8a14220296b147fbafe1220c)
promenio si url ali je zato odlazak na druge stranice sa te stranice sada pogrešan

![image](https://user-images.githubusercontent.com/16023196/28153538-32113644-67a6-11e7-8787-f28a39ab90d1.png)

**Comment by XoDevCom** [comment]
Ukljucio sam header koji se (pogresno) svuda koristi... sredicu...  nice catch
